### ISSUE TITLE
CURL ERROR octo REST API post create release and deploy

### ISSUE THREAD

**Issue by enriqueescobar-askida** [OctopusDeploy/OctopusDeploy-Api#27]
hi,
I cannot deploy a release created with CURL on jenkins,
It creates the release but teh release does not run the workflow 👎 :'(

#!/bin/sh -x
curl --request POST \
  --url http://build-dev-hs.axon-id.loc:8080/api/releases?ignoreChannelRules=false -H "X-Octopus-ApiKey: API-$apikey" --data "{

    'Projectid':  'Projects-3',
    'ProjectId':  'Projects-81',
    'ChannelId':  'Channels-82',
    'Version': $aVersion,
    'ReleaseNotes':  'The release notes for HydroCare.Data with -- '

}"

**Comment by matt-richardson** [comment]
Hi @enriqueescobar-askida, thanks for getting in touch.

Do you have a lifecycle setup that auto-deploys to the first environment? If thats not the case, then you'll have to create a deployment and trigger that as well.

Your best bet is to open up your browsers dev tools and watch the network traffic that happens when you perform the actions in the UI - everything that the UI does is via the API.

Hope that helps!

**Comment by matt-richardson** [comment]
Closing due to no response. If you require further assistance, please contact us via our [support channels](https://octopus.com/support).
