### ISSUE TITLE
Creating tenant variables?

### ISSUE THREAD

**Issue by ffMathy** [OctopusDeploy/OctopusDeploy-Api#35]
Currently in the documentation there are only GET operations for tenant variables. Is this really true? If so, the company I work for can't currently use Octopus.

**Comment by droyad** [comment]
@ffMathy I think you may be looking at the `TentantVariables` doc page, which lists all the variables. I'm not sure why the `/api/tenants/{id}/variables` is there, that is probably a mistake. 

Have a look at the `Tenants` API doc page (https://github.com/OctopusDeploy/OctopusDeploy-Api/wiki/Tenants) there you will see the APIs for updating the variables.

The Octopus UI uses the API, so anything that can be done in the UI, can be done via the API (and more).

Also since `3.17` we have included [swagger documentation](https://octopus.com/blog/octopus-release-3-17#swagger-support-for-the-octopus-api). While does not document the usage, it does show all the APIs and methods available.

**Comment by ffMathy** [comment]
The swagger documentation is also outdated in this regard, and doesn't show what kind of `POST` body is required to update the variables through this endpoint.

Can you help me with that?

**Comment by droyad** [comment]
@ffMathy If you expand the item, eg https://demo.octopusdeploy.com/swaggerui/index.html#/Tenants/post_api_tenants__id__variables it will show an example value as well as the model. You can also look at the https://github.com/OctopusDeploy/OctopusClients source code

**Comment by ffMathy** [comment]
That shows the response model, not the request model. I assume it's not the same?

**Comment by droyad** [comment]
The models are the same in and out, our API works on a "resource" model, not "operation" model.

Leave out the things filled in by the server (eg new Ids, updated dates, etc). If in doubt inspect the calls the UI makes when doing the operation.

**Comment by droyad** [comment]
@distantcam Should we add the request objects to the swagger document?

**Comment by distantcam** [comment]
@droyad That's the plan.
